-- AlterTable
ALTER TABLE `Offers` ADD COLUMN `region` ENUM('DOLNOSLASKIE', 'KUJAWSKOPOMORSKIE', 'LUBELSKIE', 'LUBUSKIE', 'LODZKIE', 'MALOPOLSKIE', 'MAZOWIECKIE', 'OPOLSKIE', 'PODKARPACKIE', 'PODLASKIE', 'POMORSKIE', 'SLASKIE', 'SWIETOKRZYSKIE', 'WARMINSKOMAZURSKIE', 'WIELKOPOLSKIE', 'ZACHODNIOPOMORSKIE') NULL;
